### PR TITLE
Lu side nav bar

### PR DESCRIPTION
**Pull request by LUXIANZE**
Check and acquire change if needed.

### CODE REVIEW

**Comment by HowardYaw** [comment]
Side bar button will place over the text<br>
image

**Comment by HowardYaw** [comment]
Since the info page is set to with fullheight class, because there are much content so it will overflow to next page<br>
- Either we make the content fit to one page
- Or we make the info page not fullheight(100vh)
image

**Comment by HowardYaw** [comment]
Sidebar: <br>
- once clicked on the link in sidebar need to close the sidebar?
- are you gonna push the content when sidebar open?

**Comment by LUXIANZE** [comment]
- Hmmm, i start to think that, the height should be, >= fullheight. if more than full height then set to suit the content. The reason I want fullheight is to avoid viewing different content at the same time
- I dont think should close the side bar after navigating, since have the close button for them to use ady
- I'll add push to side on expand

**Pull request merged**
